// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: jwts_v1/jwk.proto

package jwts_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JwkSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []*JwkMain `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *JwkSet) Reset() {
	*x = JwkSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwts_v1_jwk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JwkSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwkSet) ProtoMessage() {}

func (x *JwkSet) ProtoReflect() protoreflect.Message {
	mi := &file_jwts_v1_jwk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwkSet.ProtoReflect.Descriptor instead.
func (*JwkSet) Descriptor() ([]byte, []int) {
	return file_jwts_v1_jwk_proto_rawDescGZIP(), []int{0}
}

func (x *JwkSet) GetKeys() []*JwkMain {
	if x != nil {
		return x.Keys
	}
	return nil
}

type JwkMain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kty string `protobuf:"bytes,1,opt,name=kty,proto3" json:"kty,omitempty"`
	E   string `protobuf:"bytes,2,opt,name=e,proto3" json:"e,omitempty"`
	Kid string `protobuf:"bytes,3,opt,name=kid,proto3" json:"kid,omitempty"`
	Alg string `protobuf:"bytes,4,opt,name=alg,proto3" json:"alg,omitempty"`
	N   string `protobuf:"bytes,5,opt,name=n,proto3" json:"n,omitempty"`
	Use string `protobuf:"bytes,6,opt,name=use,proto3" json:"use,omitempty"`
}

func (x *JwkMain) Reset() {
	*x = JwkMain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwts_v1_jwk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JwkMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwkMain) ProtoMessage() {}

func (x *JwkMain) ProtoReflect() protoreflect.Message {
	mi := &file_jwts_v1_jwk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwkMain.ProtoReflect.Descriptor instead.
func (*JwkMain) Descriptor() ([]byte, []int) {
	return file_jwts_v1_jwk_proto_rawDescGZIP(), []int{1}
}

func (x *JwkMain) GetKty() string {
	if x != nil {
		return x.Kty
	}
	return ""
}

func (x *JwkMain) GetE() string {
	if x != nil {
		return x.E
	}
	return ""
}

func (x *JwkMain) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *JwkMain) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *JwkMain) GetN() string {
	if x != nil {
		return x.N
	}
	return ""
}

func (x *JwkMain) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

var File_jwts_v1_jwk_proto protoreflect.FileDescriptor

var file_jwts_v1_jwk_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6a, 0x77, 0x74, 0x73, 0x5f, 0x76, 0x31, 0x2f, 0x6a, 0x77, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6a, 0x77, 0x74, 0x73, 0x5f, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x06, 0x4a, 0x77, 0x6b,
	0x53, 0x65, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x6a, 0x77, 0x74, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x4a, 0x77, 0x6b, 0x4d,
	0x61, 0x69, 0x6e, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x6d, 0x0a, 0x07, 0x4a, 0x77, 0x6b,
	0x4d, 0x61, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x74, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x01, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x6c, 0x67, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x6c, 0x67, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x01, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x73, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x73, 0x65, 0x32, 0x35, 0x0a, 0x03, 0x4a, 0x77, 0x6b, 0x12,
	0x2e, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0f,
	0x2e, 0x6a, 0x77, 0x74, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x4a, 0x77, 0x6b, 0x53, 0x65, 0x74, 0x42,
	0x0a, 0x5a, 0x08, 0x2f, 0x6a, 0x77, 0x74, 0x73, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_jwts_v1_jwk_proto_rawDescOnce sync.Once
	file_jwts_v1_jwk_proto_rawDescData = file_jwts_v1_jwk_proto_rawDesc
)

func file_jwts_v1_jwk_proto_rawDescGZIP() []byte {
	file_jwts_v1_jwk_proto_rawDescOnce.Do(func() {
		file_jwts_v1_jwk_proto_rawDescData = protoimpl.X.CompressGZIP(file_jwts_v1_jwk_proto_rawDescData)
	})
	return file_jwts_v1_jwk_proto_rawDescData
}

var file_jwts_v1_jwk_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jwts_v1_jwk_proto_goTypes = []interface{}{
	(*JwkSet)(nil),        // 0: jwts_v1.JwkSet
	(*JwkMain)(nil),       // 1: jwts_v1.JwkMain
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_jwts_v1_jwk_proto_depIdxs = []int32{
	1, // 0: jwts_v1.JwkSet.keys:type_name -> jwts_v1.JwkMain
	2, // 1: jwts_v1.Jwk.Get:input_type -> google.protobuf.Empty
	0, // 2: jwts_v1.Jwk.Get:output_type -> jwts_v1.JwkSet
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_jwts_v1_jwk_proto_init() }
func file_jwts_v1_jwk_proto_init() {
	if File_jwts_v1_jwk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jwts_v1_jwk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JwkSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jwts_v1_jwk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JwkMain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jwts_v1_jwk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jwts_v1_jwk_proto_goTypes,
		DependencyIndexes: file_jwts_v1_jwk_proto_depIdxs,
		MessageInfos:      file_jwts_v1_jwk_proto_msgTypes,
	}.Build()
	File_jwts_v1_jwk_proto = out.File
	file_jwts_v1_jwk_proto_rawDesc = nil
	file_jwts_v1_jwk_proto_goTypes = nil
	file_jwts_v1_jwk_proto_depIdxs = nil
}
