// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: jwts_v1/jwk.proto

package jwts_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JwkSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*JwkMain             `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwkSet) Reset() {
	*x = JwkSet{}
	mi := &file_jwts_v1_jwk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwkSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwkSet) ProtoMessage() {}

func (x *JwkSet) ProtoReflect() protoreflect.Message {
	mi := &file_jwts_v1_jwk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwkSet.ProtoReflect.Descriptor instead.
func (*JwkSet) Descriptor() ([]byte, []int) {
	return file_jwts_v1_jwk_proto_rawDescGZIP(), []int{0}
}

func (x *JwkSet) GetKeys() []*JwkMain {
	if x != nil {
		return x.Keys
	}
	return nil
}

type JwkMain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kty           string                 `protobuf:"bytes,1,opt,name=kty,proto3" json:"kty,omitempty"`
	E             string                 `protobuf:"bytes,2,opt,name=e,proto3" json:"e,omitempty"`
	Kid           string                 `protobuf:"bytes,3,opt,name=kid,proto3" json:"kid,omitempty"`
	Alg           string                 `protobuf:"bytes,4,opt,name=alg,proto3" json:"alg,omitempty"`
	N             string                 `protobuf:"bytes,5,opt,name=n,proto3" json:"n,omitempty"`
	Use           string                 `protobuf:"bytes,6,opt,name=use,proto3" json:"use,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwkMain) Reset() {
	*x = JwkMain{}
	mi := &file_jwts_v1_jwk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwkMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwkMain) ProtoMessage() {}

func (x *JwkMain) ProtoReflect() protoreflect.Message {
	mi := &file_jwts_v1_jwk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwkMain.ProtoReflect.Descriptor instead.
func (*JwkMain) Descriptor() ([]byte, []int) {
	return file_jwts_v1_jwk_proto_rawDescGZIP(), []int{1}
}

func (x *JwkMain) GetKty() string {
	if x != nil {
		return x.Kty
	}
	return ""
}

func (x *JwkMain) GetE() string {
	if x != nil {
		return x.E
	}
	return ""
}

func (x *JwkMain) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *JwkMain) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *JwkMain) GetN() string {
	if x != nil {
		return x.N
	}
	return ""
}

func (x *JwkMain) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

var File_jwts_v1_jwk_proto protoreflect.FileDescriptor

const file_jwts_v1_jwk_proto_rawDesc = "" +
	"\n" +
	"\x11jwts_v1/jwk.proto\x12\ajwts_v1\x1a\x1bgoogle/protobuf/empty.proto\".\n" +
	"\x06JwkSet\x12$\n" +
	"\x04keys\x18\x01 \x03(\v2\x10.jwts_v1.JwkMainR\x04keys\"m\n" +
	"\aJwkMain\x12\x10\n" +
	"\x03kty\x18\x01 \x01(\tR\x03kty\x12\f\n" +
	"\x01e\x18\x02 \x01(\tR\x01e\x12\x10\n" +
	"\x03kid\x18\x03 \x01(\tR\x03kid\x12\x10\n" +
	"\x03alg\x18\x04 \x01(\tR\x03alg\x12\f\n" +
	"\x01n\x18\x05 \x01(\tR\x01n\x12\x10\n" +
	"\x03use\x18\x06 \x01(\tR\x03use25\n" +
	"\x03Jwk\x12.\n" +
	"\x03Get\x12\x16.google.protobuf.Empty\x1a\x0f.jwts_v1.JwkSetB\n" +
	"Z\b/jwts_v1b\x06proto3"

var (
	file_jwts_v1_jwk_proto_rawDescOnce sync.Once
	file_jwts_v1_jwk_proto_rawDescData []byte
)

func file_jwts_v1_jwk_proto_rawDescGZIP() []byte {
	file_jwts_v1_jwk_proto_rawDescOnce.Do(func() {
		file_jwts_v1_jwk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jwts_v1_jwk_proto_rawDesc), len(file_jwts_v1_jwk_proto_rawDesc)))
	})
	return file_jwts_v1_jwk_proto_rawDescData
}

var file_jwts_v1_jwk_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jwts_v1_jwk_proto_goTypes = []any{
	(*JwkSet)(nil),        // 0: jwts_v1.JwkSet
	(*JwkMain)(nil),       // 1: jwts_v1.JwkMain
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_jwts_v1_jwk_proto_depIdxs = []int32{
	1, // 0: jwts_v1.JwkSet.keys:type_name -> jwts_v1.JwkMain
	2, // 1: jwts_v1.Jwk.Get:input_type -> google.protobuf.Empty
	0, // 2: jwts_v1.Jwk.Get:output_type -> jwts_v1.JwkSet
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_jwts_v1_jwk_proto_init() }
func file_jwts_v1_jwk_proto_init() {
	if File_jwts_v1_jwk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jwts_v1_jwk_proto_rawDesc), len(file_jwts_v1_jwk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jwts_v1_jwk_proto_goTypes,
		DependencyIndexes: file_jwts_v1_jwk_proto_depIdxs,
		MessageInfos:      file_jwts_v1_jwk_proto_msgTypes,
	}.Build()
	File_jwts_v1_jwk_proto = out.File
	file_jwts_v1_jwk_proto_goTypes = nil
	file_jwts_v1_jwk_proto_depIdxs = nil
}
