// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: jwts_v1/jwt.proto

package jwts_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JwtCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sub        string `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	ExpSeconds int64  `protobuf:"varint,2,opt,name=exp_seconds,json=expSeconds,proto3" json:"exp_seconds,omitempty"`
	Payload    []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // json encoded payload
}

func (x *JwtCreateReq) Reset() {
	*x = JwtCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwts_v1_jwt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JwtCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtCreateReq) ProtoMessage() {}

func (x *JwtCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_jwts_v1_jwt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtCreateReq.ProtoReflect.Descriptor instead.
func (*JwtCreateReq) Descriptor() ([]byte, []int) {
	return file_jwts_v1_jwt_proto_rawDescGZIP(), []int{0}
}

func (x *JwtCreateReq) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *JwtCreateReq) GetExpSeconds() int64 {
	if x != nil {
		return x.ExpSeconds
	}
	return 0
}

func (x *JwtCreateReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type JwtCreateRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *JwtCreateRep) Reset() {
	*x = JwtCreateRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwts_v1_jwt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JwtCreateRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtCreateRep) ProtoMessage() {}

func (x *JwtCreateRep) ProtoReflect() protoreflect.Message {
	mi := &file_jwts_v1_jwt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtCreateRep.ProtoReflect.Descriptor instead.
func (*JwtCreateRep) Descriptor() ([]byte, []int) {
	return file_jwts_v1_jwt_proto_rawDescGZIP(), []int{1}
}

func (x *JwtCreateRep) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JwtValidateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *JwtValidateReq) Reset() {
	*x = JwtValidateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwts_v1_jwt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JwtValidateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtValidateReq) ProtoMessage() {}

func (x *JwtValidateReq) ProtoReflect() protoreflect.Message {
	mi := &file_jwts_v1_jwt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtValidateReq.ProtoReflect.Descriptor instead.
func (*JwtValidateReq) Descriptor() ([]byte, []int) {
	return file_jwts_v1_jwt_proto_rawDescGZIP(), []int{2}
}

func (x *JwtValidateReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JwtValidateRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid  bool   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Claims []byte `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
}

func (x *JwtValidateRep) Reset() {
	*x = JwtValidateRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwts_v1_jwt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JwtValidateRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtValidateRep) ProtoMessage() {}

func (x *JwtValidateRep) ProtoReflect() protoreflect.Message {
	mi := &file_jwts_v1_jwt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtValidateRep.ProtoReflect.Descriptor instead.
func (*JwtValidateRep) Descriptor() ([]byte, []int) {
	return file_jwts_v1_jwt_proto_rawDescGZIP(), []int{3}
}

func (x *JwtValidateRep) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *JwtValidateRep) GetClaims() []byte {
	if x != nil {
		return x.Claims
	}
	return nil
}

var File_jwts_v1_jwt_proto protoreflect.FileDescriptor

var file_jwts_v1_jwt_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6a, 0x77, 0x74, 0x73, 0x5f, 0x76, 0x31, 0x2f, 0x6a, 0x77, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6a, 0x77, 0x74, 0x73, 0x5f, 0x76, 0x31, 0x22, 0x5b, 0x0a, 0x0c,
	0x4a, 0x77, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x75, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x75, 0x62, 0x12, 0x1f,
	0x0a, 0x0b, 0x65, 0x78, 0x70, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x24, 0x0a, 0x0c, 0x4a, 0x77, 0x74,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x26, 0x0a, 0x0e, 0x4a, 0x77, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x3e, 0x0a, 0x0e, 0x4a, 0x77, 0x74, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x32, 0x7b, 0x0a, 0x03, 0x4a, 0x77, 0x74, 0x12, 0x36,
	0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x6a, 0x77, 0x74, 0x73, 0x5f,
	0x76, 0x31, 0x2e, 0x4a, 0x77, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x15, 0x2e, 0x6a, 0x77, 0x74, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x4a, 0x77, 0x74, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x12, 0x3c, 0x0a, 0x08, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x17, 0x2e, 0x6a, 0x77, 0x74, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x4a, 0x77, 0x74,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x6a, 0x77,
	0x74, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x4a, 0x77, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x70, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x6a, 0x77, 0x74, 0x73, 0x5f, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jwts_v1_jwt_proto_rawDescOnce sync.Once
	file_jwts_v1_jwt_proto_rawDescData = file_jwts_v1_jwt_proto_rawDesc
)

func file_jwts_v1_jwt_proto_rawDescGZIP() []byte {
	file_jwts_v1_jwt_proto_rawDescOnce.Do(func() {
		file_jwts_v1_jwt_proto_rawDescData = protoimpl.X.CompressGZIP(file_jwts_v1_jwt_proto_rawDescData)
	})
	return file_jwts_v1_jwt_proto_rawDescData
}

var file_jwts_v1_jwt_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_jwts_v1_jwt_proto_goTypes = []interface{}{
	(*JwtCreateReq)(nil),   // 0: jwts_v1.JwtCreateReq
	(*JwtCreateRep)(nil),   // 1: jwts_v1.JwtCreateRep
	(*JwtValidateReq)(nil), // 2: jwts_v1.JwtValidateReq
	(*JwtValidateRep)(nil), // 3: jwts_v1.JwtValidateRep
}
var file_jwts_v1_jwt_proto_depIdxs = []int32{
	0, // 0: jwts_v1.Jwt.Create:input_type -> jwts_v1.JwtCreateReq
	2, // 1: jwts_v1.Jwt.Validate:input_type -> jwts_v1.JwtValidateReq
	1, // 2: jwts_v1.Jwt.Create:output_type -> jwts_v1.JwtCreateRep
	3, // 3: jwts_v1.Jwt.Validate:output_type -> jwts_v1.JwtValidateRep
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jwts_v1_jwt_proto_init() }
func file_jwts_v1_jwt_proto_init() {
	if File_jwts_v1_jwt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jwts_v1_jwt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JwtCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jwts_v1_jwt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JwtCreateRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jwts_v1_jwt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JwtValidateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jwts_v1_jwt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JwtValidateRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jwts_v1_jwt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jwts_v1_jwt_proto_goTypes,
		DependencyIndexes: file_jwts_v1_jwt_proto_depIdxs,
		MessageInfos:      file_jwts_v1_jwt_proto_msgTypes,
	}.Build()
	File_jwts_v1_jwt_proto = out.File
	file_jwts_v1_jwt_proto_rawDesc = nil
	file_jwts_v1_jwt_proto_goTypes = nil
	file_jwts_v1_jwt_proto_depIdxs = nil
}
