// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: jwts_v1/jwt.proto

package jwts_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JwtCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sub           string                 `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	ExpSeconds    int64                  `protobuf:"varint,2,opt,name=exp_seconds,json=expSeconds,proto3" json:"exp_seconds,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // json encoded payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtCreateReq) Reset() {
	*x = JwtCreateReq{}
	mi := &file_jwts_v1_jwt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtCreateReq) ProtoMessage() {}

func (x *JwtCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_jwts_v1_jwt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtCreateReq.ProtoReflect.Descriptor instead.
func (*JwtCreateReq) Descriptor() ([]byte, []int) {
	return file_jwts_v1_jwt_proto_rawDescGZIP(), []int{0}
}

func (x *JwtCreateReq) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *JwtCreateReq) GetExpSeconds() int64 {
	if x != nil {
		return x.ExpSeconds
	}
	return 0
}

func (x *JwtCreateReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type JwtCreateRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtCreateRep) Reset() {
	*x = JwtCreateRep{}
	mi := &file_jwts_v1_jwt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtCreateRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtCreateRep) ProtoMessage() {}

func (x *JwtCreateRep) ProtoReflect() protoreflect.Message {
	mi := &file_jwts_v1_jwt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtCreateRep.ProtoReflect.Descriptor instead.
func (*JwtCreateRep) Descriptor() ([]byte, []int) {
	return file_jwts_v1_jwt_proto_rawDescGZIP(), []int{1}
}

func (x *JwtCreateRep) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JwtValidateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtValidateReq) Reset() {
	*x = JwtValidateReq{}
	mi := &file_jwts_v1_jwt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtValidateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtValidateReq) ProtoMessage() {}

func (x *JwtValidateReq) ProtoReflect() protoreflect.Message {
	mi := &file_jwts_v1_jwt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtValidateReq.ProtoReflect.Descriptor instead.
func (*JwtValidateReq) Descriptor() ([]byte, []int) {
	return file_jwts_v1_jwt_proto_rawDescGZIP(), []int{2}
}

func (x *JwtValidateReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JwtValidateRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Claims        []byte                 `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtValidateRep) Reset() {
	*x = JwtValidateRep{}
	mi := &file_jwts_v1_jwt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtValidateRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtValidateRep) ProtoMessage() {}

func (x *JwtValidateRep) ProtoReflect() protoreflect.Message {
	mi := &file_jwts_v1_jwt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtValidateRep.ProtoReflect.Descriptor instead.
func (*JwtValidateRep) Descriptor() ([]byte, []int) {
	return file_jwts_v1_jwt_proto_rawDescGZIP(), []int{3}
}

func (x *JwtValidateRep) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *JwtValidateRep) GetClaims() []byte {
	if x != nil {
		return x.Claims
	}
	return nil
}

var File_jwts_v1_jwt_proto protoreflect.FileDescriptor

const file_jwts_v1_jwt_proto_rawDesc = "" +
	"\n" +
	"\x11jwts_v1/jwt.proto\x12\ajwts_v1\"[\n" +
	"\fJwtCreateReq\x12\x10\n" +
	"\x03sub\x18\x01 \x01(\tR\x03sub\x12\x1f\n" +
	"\vexp_seconds\x18\x02 \x01(\x03R\n" +
	"expSeconds\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"$\n" +
	"\fJwtCreateRep\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"&\n" +
	"\x0eJwtValidateReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\">\n" +
	"\x0eJwtValidateRep\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06claims\x18\x02 \x01(\fR\x06claims2{\n" +
	"\x03Jwt\x126\n" +
	"\x06Create\x12\x15.jwts_v1.JwtCreateReq\x1a\x15.jwts_v1.JwtCreateRep\x12<\n" +
	"\bValidate\x12\x17.jwts_v1.JwtValidateReq\x1a\x17.jwts_v1.JwtValidateRepB\n" +
	"Z\b/jwts_v1b\x06proto3"

var (
	file_jwts_v1_jwt_proto_rawDescOnce sync.Once
	file_jwts_v1_jwt_proto_rawDescData []byte
)

func file_jwts_v1_jwt_proto_rawDescGZIP() []byte {
	file_jwts_v1_jwt_proto_rawDescOnce.Do(func() {
		file_jwts_v1_jwt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jwts_v1_jwt_proto_rawDesc), len(file_jwts_v1_jwt_proto_rawDesc)))
	})
	return file_jwts_v1_jwt_proto_rawDescData
}

var file_jwts_v1_jwt_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_jwts_v1_jwt_proto_goTypes = []any{
	(*JwtCreateReq)(nil),   // 0: jwts_v1.JwtCreateReq
	(*JwtCreateRep)(nil),   // 1: jwts_v1.JwtCreateRep
	(*JwtValidateReq)(nil), // 2: jwts_v1.JwtValidateReq
	(*JwtValidateRep)(nil), // 3: jwts_v1.JwtValidateRep
}
var file_jwts_v1_jwt_proto_depIdxs = []int32{
	0, // 0: jwts_v1.Jwt.Create:input_type -> jwts_v1.JwtCreateReq
	2, // 1: jwts_v1.Jwt.Validate:input_type -> jwts_v1.JwtValidateReq
	1, // 2: jwts_v1.Jwt.Create:output_type -> jwts_v1.JwtCreateRep
	3, // 3: jwts_v1.Jwt.Validate:output_type -> jwts_v1.JwtValidateRep
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jwts_v1_jwt_proto_init() }
func file_jwts_v1_jwt_proto_init() {
	if File_jwts_v1_jwt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jwts_v1_jwt_proto_rawDesc), len(file_jwts_v1_jwt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jwts_v1_jwt_proto_goTypes,
		DependencyIndexes: file_jwts_v1_jwt_proto_depIdxs,
		MessageInfos:      file_jwts_v1_jwt_proto_msgTypes,
	}.Build()
	File_jwts_v1_jwt_proto = out.File
	file_jwts_v1_jwt_proto_goTypes = nil
	file_jwts_v1_jwt_proto_depIdxs = nil
}
